// Code generated by MockGen. DO NOT EDIT.
// Source: pet_service_interface.go
//
// Generated by this command:
//
//	mockgen -source=pet_service_interface.go -destination=../mocks/mock_pet_service.go -package=mocks github.com/maakh3/api-petstore-service-layer/services PetServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/maakh3/api-petstore-service-layer/models"
	gomock "go.uber.org/mock/gomock"
)

// MockPetServiceInterface is a mock of PetServiceInterface interface.
type MockPetServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPetServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockPetServiceInterfaceMockRecorder is the mock recorder for MockPetServiceInterface.
type MockPetServiceInterfaceMockRecorder struct {
	mock *MockPetServiceInterface
}

// NewMockPetServiceInterface creates a new mock instance.
func NewMockPetServiceInterface(ctrl *gomock.Controller) *MockPetServiceInterface {
	mock := &MockPetServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPetServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPetServiceInterface) EXPECT() *MockPetServiceInterfaceMockRecorder {
	return m.recorder
}

// AddPet mocks base method.
func (m *MockPetServiceInterface) AddPet(pet models.Pet) (models.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPet", pet)
	ret0, _ := ret[0].(models.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPet indicates an expected call of AddPet.
func (mr *MockPetServiceInterfaceMockRecorder) AddPet(pet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPet", reflect.TypeOf((*MockPetServiceInterface)(nil).AddPet), pet)
}

// FindPetsByStatus mocks base method.
func (m *MockPetServiceInterface) FindPetsByStatus(status string) ([]models.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPetsByStatus", status)
	ret0, _ := ret[0].([]models.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPetsByStatus indicates an expected call of FindPetsByStatus.
func (mr *MockPetServiceInterfaceMockRecorder) FindPetsByStatus(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPetsByStatus", reflect.TypeOf((*MockPetServiceInterface)(nil).FindPetsByStatus), status)
}

// FindPetsByTags mocks base method.
func (m *MockPetServiceInterface) FindPetsByTags(tags []models.Tag) ([]models.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPetsByTags", tags)
	ret0, _ := ret[0].([]models.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPetsByTags indicates an expected call of FindPetsByTags.
func (mr *MockPetServiceInterfaceMockRecorder) FindPetsByTags(tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPetsByTags", reflect.TypeOf((*MockPetServiceInterface)(nil).FindPetsByTags), tags)
}

// GetById mocks base method.
func (m *MockPetServiceInterface) GetById(id int) (models.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(models.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockPetServiceInterfaceMockRecorder) GetById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockPetServiceInterface)(nil).GetById), id)
}

// UpdatePet mocks base method.
func (m *MockPetServiceInterface) UpdatePet(pet models.Pet) (models.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePet", pet)
	ret0, _ := ret[0].(models.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePet indicates an expected call of UpdatePet.
func (mr *MockPetServiceInterfaceMockRecorder) UpdatePet(pet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePet", reflect.TypeOf((*MockPetServiceInterface)(nil).UpdatePet), pet)
}
