// Code generated by MockGen. DO NOT EDIT.
// Source: pet_handler_interface.go
//
// Generated by this command:
//
//	mockgen -source=pet_handler_interface.go -destination=../mocks/mock_pet_handler.go -package=mocks github.com/maakh3/api-petstore-service-layer/handler PetHandlerInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPetHandlerInterface is a mock of PetHandlerInterface interface.
type MockPetHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPetHandlerInterfaceMockRecorder
	isgomock struct{}
}

// MockPetHandlerInterfaceMockRecorder is the mock recorder for MockPetHandlerInterface.
type MockPetHandlerInterfaceMockRecorder struct {
	mock *MockPetHandlerInterface
}

// NewMockPetHandlerInterface creates a new mock instance.
func NewMockPetHandlerInterface(ctrl *gomock.Controller) *MockPetHandlerInterface {
	mock := &MockPetHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockPetHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPetHandlerInterface) EXPECT() *MockPetHandlerInterfaceMockRecorder {
	return m.recorder
}

// AddPet mocks base method.
func (m *MockPetHandlerInterface) AddPet(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddPet", w, r)
}

// AddPet indicates an expected call of AddPet.
func (mr *MockPetHandlerInterfaceMockRecorder) AddPet(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPet", reflect.TypeOf((*MockPetHandlerInterface)(nil).AddPet), w, r)
}

// FindPetsByStatus mocks base method.
func (m *MockPetHandlerInterface) FindPetsByStatus(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FindPetsByStatus", w, r)
}

// FindPetsByStatus indicates an expected call of FindPetsByStatus.
func (mr *MockPetHandlerInterfaceMockRecorder) FindPetsByStatus(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPetsByStatus", reflect.TypeOf((*MockPetHandlerInterface)(nil).FindPetsByStatus), w, r)
}

// FindPetsByTags mocks base method.
func (m *MockPetHandlerInterface) FindPetsByTags(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FindPetsByTags", w, r)
}

// FindPetsByTags indicates an expected call of FindPetsByTags.
func (mr *MockPetHandlerInterfaceMockRecorder) FindPetsByTags(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPetsByTags", reflect.TypeOf((*MockPetHandlerInterface)(nil).FindPetsByTags), w, r)
}

// GetById mocks base method.
func (m *MockPetHandlerInterface) GetById(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetById", w, r)
}

// GetById indicates an expected call of GetById.
func (mr *MockPetHandlerInterfaceMockRecorder) GetById(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockPetHandlerInterface)(nil).GetById), w, r)
}

// UpdatePet mocks base method.
func (m *MockPetHandlerInterface) UpdatePet(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdatePet", w, r)
}

// UpdatePet indicates an expected call of UpdatePet.
func (mr *MockPetHandlerInterfaceMockRecorder) UpdatePet(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePet", reflect.TypeOf((*MockPetHandlerInterface)(nil).UpdatePet), w, r)
}
