// Code generated by MockGen. DO NOT EDIT.
// Source: pet_repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=pet_repository_interface.go -destination=../mocks/mock_pet_repository.go -package=mocks github.com/maakh3/api-petstore-service-layer/repository PetRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/maakh3/api-petstore-service-layer/models"
	gomock "go.uber.org/mock/gomock"
)

// MockPetRepositoryInterface is a mock of PetRepositoryInterface interface.
type MockPetRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPetRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockPetRepositoryInterfaceMockRecorder is the mock recorder for MockPetRepositoryInterface.
type MockPetRepositoryInterfaceMockRecorder struct {
	mock *MockPetRepositoryInterface
}

// NewMockPetRepositoryInterface creates a new mock instance.
func NewMockPetRepositoryInterface(ctrl *gomock.Controller) *MockPetRepositoryInterface {
	mock := &MockPetRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockPetRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPetRepositoryInterface) EXPECT() *MockPetRepositoryInterfaceMockRecorder {
	return m.recorder
}

// AddPet mocks base method.
func (m *MockPetRepositoryInterface) AddPet(pet models.Pet) (models.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPet", pet)
	ret0, _ := ret[0].(models.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPet indicates an expected call of AddPet.
func (mr *MockPetRepositoryInterfaceMockRecorder) AddPet(pet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPet", reflect.TypeOf((*MockPetRepositoryInterface)(nil).AddPet), pet)
}

// DeletePet mocks base method.
func (m *MockPetRepositoryInterface) DeletePet(id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePet", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePet indicates an expected call of DeletePet.
func (mr *MockPetRepositoryInterfaceMockRecorder) DeletePet(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePet", reflect.TypeOf((*MockPetRepositoryInterface)(nil).DeletePet), id)
}

// FindPetsByStatus mocks base method.
func (m *MockPetRepositoryInterface) FindPetsByStatus(status string) ([]models.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPetsByStatus", status)
	ret0, _ := ret[0].([]models.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPetsByStatus indicates an expected call of FindPetsByStatus.
func (mr *MockPetRepositoryInterfaceMockRecorder) FindPetsByStatus(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPetsByStatus", reflect.TypeOf((*MockPetRepositoryInterface)(nil).FindPetsByStatus), status)
}

// FindPetsByTags mocks base method.
func (m *MockPetRepositoryInterface) FindPetsByTags(tags []models.Tag) ([]models.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPetsByTags", tags)
	ret0, _ := ret[0].([]models.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPetsByTags indicates an expected call of FindPetsByTags.
func (mr *MockPetRepositoryInterfaceMockRecorder) FindPetsByTags(tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPetsByTags", reflect.TypeOf((*MockPetRepositoryInterface)(nil).FindPetsByTags), tags)
}

// GetById mocks base method.
func (m *MockPetRepositoryInterface) GetById(id int64) (models.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(models.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockPetRepositoryInterfaceMockRecorder) GetById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockPetRepositoryInterface)(nil).GetById), id)
}

// UpdatePet mocks base method.
func (m *MockPetRepositoryInterface) UpdatePet(pet models.Pet) (models.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePet", pet)
	ret0, _ := ret[0].(models.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePet indicates an expected call of UpdatePet.
func (mr *MockPetRepositoryInterfaceMockRecorder) UpdatePet(pet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePet", reflect.TypeOf((*MockPetRepositoryInterface)(nil).UpdatePet), pet)
}

// UpdatePetByForm mocks base method.
func (m *MockPetRepositoryInterface) UpdatePetByForm(id int64, name, status *string) (models.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePetByForm", id, name, status)
	ret0, _ := ret[0].(models.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePetByForm indicates an expected call of UpdatePetByForm.
func (mr *MockPetRepositoryInterfaceMockRecorder) UpdatePetByForm(id, name, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePetByForm", reflect.TypeOf((*MockPetRepositoryInterface)(nil).UpdatePetByForm), id, name, status)
}

// UploadImage mocks base method.
func (m *MockPetRepositoryInterface) UploadImage(id int64, imageUrl string) (models.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImage", id, imageUrl)
	ret0, _ := ret[0].(models.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadImage indicates an expected call of UploadImage.
func (mr *MockPetRepositoryInterfaceMockRecorder) UploadImage(id, imageUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImage", reflect.TypeOf((*MockPetRepositoryInterface)(nil).UploadImage), id, imageUrl)
}
